# -*- coding: utf-8 -*-
"""DL1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IPrAzOCDHwymlOLGf3XNKoaSFXx4_emS
"""

import numpy as np
import tensorflow as tf
from tensorflow.keras.datasets import boston_housing
!pip install sklearn
from sklearn.preprocessing import StandardScaler

(x_train,y_train),(x_test,y_test)=boston_housing.load_data()

x=np.concatenate((x_train,x_test), axis=0)
y=np.concatenate((y_train,y_test), axis=0).reshape(-1,1)

scalar=StandardScaler()
x=scalar.fit_transform(x)

model = tf.keras.models.Sequential( [
     tf.keras.layers.Dense(64, activation= 'relu' , input_shape=[13]),
     tf.keras.layers.Dense(64, activation= 'relu'),
     tf. keras . layers . Dense (1)
])

model.compile(optimizer= 'adam',loss= 'mse',metrics=['mae', 'mse'])

history=model.fit(x,y,epochs=100,validation_split=0.2)

new_x=np.array([[0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98]])
new_X=scalar.transform(new_x)
pred=model.predict(new_X)
print(pred)